// <auto-generated />
using System;
using CarFleetAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarFleetAPI.Migrations
{
    [DbContext(typeof(VehicleInfoContext))]
    [Migration("20220302202549_VehicleInfoDbInitilaMigration")]
    partial class VehicleInfoDbInitilaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("CarFleetAPI.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CurrentX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentY")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoadCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Model = "Mercedes",
                            RegistrationNumber = "ST-111-AA"
                        },
                        new
                        {
                            Id = 2,
                            Model = "Volovo",
                            RegistrationNumber = "ST-222-BB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
